Update build-padavan.yml

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -1,104 +1,92 @@
-#修改TNAME: MI-3G 中的 MI-3G 为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
 name: Build Padavan
 
-on: 
-  release:
-    types: [published]
-  push:
-    tags:
-    - 'v*'
-  watch:
-    types: [started]
+on:
+  workflow_dispatch:
 
 jobs:
   build:
-    runs-on: ubuntu-20.04  # 👈 关键点：已经帮你换成目前支持的 20.04 系统，绝不再卡死
-    if: github.event.repository.owner.id == github.event.sender.id
+    runs-on: ubuntu-22.04
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@master
-    - name: Initialization environment
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        sudo apt-get update
-        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
-        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
-        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
-    - name: Clone source code
-      env:
-        KERNEL: 3.4
-      run: |
-        if [ $KERNEL = "4.4" ] ; then
-        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
-        else
-        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
-        fi
-        cd /opt/rt-n56u/toolchain-mipsel
-        sh dl_toolchain.sh
-        mkdir -p /opt/images/
-    - name: Build Firmware
-      env:
-        TNAME: MI-3G      # 👈 小米路由器 3G 专属代号
-        KERNEL: 3.4
-      run: |
-        cd /opt/rt-n56u/trunk
-        if [ ! -f configs/templates/$TNAME.config ] ; then
-        echo "configs/templates/$TNAME.config not found "
-        exit 1
-        fi
-        cp -f configs/templates/$TNAME.config .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
-        
-        # 针对小米3G超实用精简配置：砍掉所有大体积插件，仅保留核心科学上网
-        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config
-        
-        sudo ./clear_tree
-        sudo ./build_firmware_modify $TNAME 0
-        sudo mv -f images/*.trx /opt/images/
-    - name : Upload packages
-      uses: actions/upload-artifact@master
-      if: always()
-      with:
-        name: Padavan-packages
-        path: /opt/images
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Initialization environment
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo apt update
+          sudo apt install -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
+          cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
+          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
+
+      - name: Clone source code
+        run: |
+          git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
+          cd /opt/rt-n56u/toolchain-mipsel
+          sh dl_toolchain.sh
+          mkdir -p /opt/images/
+
+      - name: Build Firmware
+        env:
+          TNAME: MI-3G
+        run: |
+          cd /opt/rt-n56u/trunk
+
+          if [ ! -f configs/templates/$TNAME.config ]; then
+            echo "configs/templates/$TNAME.config not found"
+            exit 1
+          fi
+
+          cp -f configs/templates/$TNAME.config .config
+
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config
+          sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config
+
+          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config
+          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config
+
+          sudo ./clear_tree
+          sudo ./build_firmware_modify $TNAME 0
+          sudo mv -f images/*.trx /opt/images/
+
+      - name: Upload firmware
+        uses: actions/upload-artifact@v4
+        with:
+          name: Padavan-packages
+          path: /opt/images/
